import Navbar from '@/components/Navbar'
import './globals.css'

import Footer from '@/components/Footer'

import CartContext from '@/context/CartContext'
import Provider from './SessionProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
      <Provider>

        <CartContext>

          <Navbar />
          {children}
          <Footer />
          
            
        </CartContext>
      </Provider>
      </body>

    </html>
  )
}
