import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'

import CartContext from '@/context/CartContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >

      <CartContext>

        <Navbar />
        {children}
        <Footer />
        
      </CartContext>
      </body>

    </html>
  )
}
